api/urls.py
from django.urls import path
from .views import DishListAPI, DishDetailAPI, OrderListAPI, OrderDetailAPI

urlpatterns = [
    path('dishs/', DishListAPI.as_view(), name='dish-list-api'),
    path('dishs/<int:pk>/', DishDetailAPI.as_view(), name='dish-detail-api'),
    path('orders/', OrderListAPI.as_view(), name='order-list-api'),
    path('orders/<int:pk>/', OrderDetailAPI.as_view(), name='order-detail-api'),
]

dishs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dishs_home, name='dishs'),
    path('add_dish/', views.add_dish, name='add_dish'),
    path('<int:pk>/update', views.DishUpdateView.as_view(), name='dish-update')
]

order_manage_syst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dishs/', include('dishs.urls')),
    path('orders/', include('orders.urls')),
    path('api/', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dishs/models.py
from django.db import models


class Dish(models.Model):
    title = models.CharField('Название', max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_available = models.BooleanField(default=True, verbose_name='Доступность') 
    id = models.AutoField(primary_key=True)
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Блюдо'
        verbose_name_plural = 'Блюда'

    def get_absolute_url(self):
        	return f'/dishs/{self.id}'

dishs/forms.py
from .models import Dish
from django.forms import ModelForm, TextInput, CheckboxInput

class DishForm(ModelForm):
    class Meta:
        model = Dish
        fields = ['title', 'price', 'is_available']

        widgets = {
            "title": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Название блюда'
            }), 
            "price": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Цена блюда'
            }),
            "is_available": CheckboxInput(attrs={
                'class': 'form-check-input', 
            }),
        } 

dishs/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from .models import Dish
from .forms import DishForm
from django.views.generic import UpdateView
from django.urls import reverse_lazy
from typing import Optional

def dishs_home(request: HttpRequest) -> HttpResponse:
    dishs = Dish.objects.all().order_by('-is_available', 'title')
    return render(request, 'dishs/dishs.html', {'dishs': dishs})

def add_dish(request: HttpRequest) -> HttpResponse:
    form_errors: Optional[dict] = None
    if request.method == 'POST':
        form = DishForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dishs')
        else:
            form_errors = form.errors 
    else:
        form = DishForm()

    data = {
        'form': form,
        'form_errors': form_errors,
    }
    return render(request, 'dishs/add_dish.html', data)

class DishUpdateView(UpdateView):
    model = Dish
    template_name = 'dishs/add_dish.html'
    form_class = DishForm
    success_url = reverse_lazy('dishs')

dishs/templates/dishs/add_dish.html
{% extends 'main/layout.html' %}

{% block title %}Форма по добавлению статьи{% endblock %}

{% block content %}
<div class="features">
    <h1>Форма по добавлению блюда</h1><br>
    <form method="post">
        {% csrf_token %}
        <!-- Выводим ошибки для каждого поля -->
        <div class="form-group">
            {{ form.title }}
            {% if form.errors.title %}
                <div class="text-danger">
                    {{ form.errors.title }}
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.price }}
            {% if form.errors.price %}
                <div class="text-danger">
                    {{ form.errors.price }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.is_available }}
            <label for="id_is_available" class="form-check-label">Доступность</label>
        </div>
        <button class="btn btn-success" type="submit">Добавить блюдо</button>
    </form>
</div>
{% endblock %}

dishs/templates/dishs/dishs.html
{% extends 'main/layout.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
        <h1>Блюда</h1>
        <a href="{% url 'add_dish' %}" class="btn btn-warning">Добавить блюдо</a>
        {% if dishs %}
        {% for el in dishs %}
            <div class = "dish">
                <h3>{{ el.title }}</h3>
                <p>{{ el.price }}</p>
                {% if el.is_available %}
                <p class="av_el">Доступно</p>
                {% else %}
                <p class="notav_el">Не доступно</p>
                {% endif %}
                <a href="{% url 'dish-update' el.id %}" class="btn btn-info">Изменить блюдо</a>
            </div>
        {% endfor %}
    {% else %}
            <p>У вас нет записей!</p>
    {% endif %}
{% endblock %}